export type Quality = 'best' | '8k' | '4k' | '2k' | '1080' | '720' | '480' | '360' | 'audio';
export type Format = 'mp4' | 'mkv' | 'webm' | 'mp3' | 'm4a' | 'opus';
export type VideoCodec = 'h264' | 'vp9' | 'av1' | 'auto';
export type AudioBitrate = 'auto' | '128';
export type SubtitleMode = 'off' | 'auto' | 'manual';
export type SubtitleFormat = 'srt' | 'vtt' | 'ass';

// Source platforms supported by yt-dlp
export type SourcePlatform = 
  | 'youtube' | 'tiktok' | 'instagram' | 'twitter' | 'facebook' 
  | 'vimeo' | 'twitch' | 'bilibili' | 'soundcloud' | 'dailymotion' | 'other';

// Settings snapshot saved with each queue item (YouTube page)
export interface ItemDownloadSettings {
  quality: Quality;
  format: Format;
  outputPath: string;
  videoCodec: VideoCodec;
  audioBitrate: AudioBitrate;
  subtitleMode: SubtitleMode;
  subtitleLangs: string[];
  subtitleEmbed: boolean;
  subtitleFormat: SubtitleFormat;
}

// Simplified settings snapshot for Universal page
export interface ItemUniversalSettings {
  quality: Quality;
  format: Format;
  outputPath: string;
  audioBitrate: AudioBitrate;
}

export interface DownloadItem {
  id: string;
  url: string;
  title: string;
  status: 'pending' | 'fetching' | 'downloading' | 'completed' | 'error';
  progress: number;
  speed: string;
  eta: string;
  error?: string;
  isPlaylist?: boolean;
  playlistIndex?: number;
  playlistTotal?: number;
  thumbnail?: string;
  duration?: string;
  channel?: string;
  filesize?: number; // File size in bytes from video info
  // Completed download info
  completedFilesize?: number; // Actual file size after download
  completedResolution?: string; // e.g. "1920x1080"
  completedFormat?: string; // e.g. "mp4"
  // Source detection
  extractor?: string; // e.g. "youtube", "tiktok", "instagram"
  // Settings snapshot when item was added to queue
  settings?: ItemDownloadSettings | ItemUniversalSettings;
}

export interface DownloadSettings {
  quality: Quality;
  format: Format;
  outputPath: string;
  downloadPlaylist: boolean;
  videoCodec: VideoCodec;
  audioBitrate: AudioBitrate;
  concurrentDownloads: number; // 1-5
  playlistLimit: number; // 0 = unlimited, 1-100
  autoCheckUpdate: boolean; // Auto check for app updates on startup
  // Subtitle settings
  subtitleMode: SubtitleMode; // off, auto, manual
  subtitleLangs: string[]; // ['vi', 'en', 'ja']
  subtitleEmbed: boolean; // true = embed into video, false = separate file
  subtitleFormat: SubtitleFormat; // srt, vtt, ass
  // YouTube specific settings
  useBunRuntime: boolean; // Use Bun runtime for YouTube downloads (fixes 360p issue)
  useActualPlayerJs: boolean; // Use actual player.js version for YouTube (fixes some download issues)
}

export interface DownloadProgress {
  id: string;
  percent: number;
  speed: string;
  eta: string;
  status: string;
  title?: string;
  playlist_index?: number;
  playlist_count?: number;
  // Additional info for completed downloads
  filesize?: number;
  resolution?: string;
  format_ext?: string;
}

export interface VideoInfo {
  id: string;
  title: string;
  thumbnail: string;
  duration: number;
  channel: string;
  upload_date: string;
  view_count: number;
  is_playlist: boolean;
  playlist_count?: number;
  // Source detection
  extractor?: string;
  extractor_key?: string;
}

export interface FormatOption {
  format_id: string;
  ext: string;
  resolution: string;
  width?: number;
  height?: number;
  vcodec: string;
  acodec: string;
  filesize?: number;
  filesize_approx?: number;
  tbr?: number;
  abr?: number;
  format_note?: string;
}

export interface VideoInfoResponse {
  info: VideoInfo;
  formats: FormatOption[];
}

export interface PlaylistInfo {
  id: string;
  title: string;
  entries: PlaylistEntry[];
}

export interface PlaylistEntry {
  id: string;
  title: string;
  url: string;
  duration?: number;
}

export interface SubtitleInfo {
  lang: string; // Language code (en, vi, ja, etc.)
  name: string; // Language name (English, Vietnamese, etc.)
  isAutoGenerated: boolean;
}

export interface PlaylistVideoEntry {
  id: string;
  title: string;
  url: string;
  thumbnail?: string;
  duration?: number;
  channel?: string;
}

// Log types
export type LogType = 'command' | 'success' | 'error' | 'stderr' | 'info';

export interface LogEntry {
  id: string;
  timestamp: string; // ISO 8601
  log_type: LogType;
  message: string;
  details?: string;
  url?: string;
}

export type LogFilter = 'all' | 'command' | 'success' | 'error' | 'stderr';

// History types
export interface HistoryEntry {
  id: string;
  url: string;
  title: string;
  thumbnail?: string;
  filepath: string;
  filesize?: number;
  duration?: number;
  quality?: string;
  format?: string;
  source?: string; // "youtube", "tiktok", etc.
  downloaded_at: string; // ISO 8601
  file_exists: boolean;
  summary?: string; // AI-generated summary
}

export type HistoryFilter = 'all' | 'youtube' | 'tiktok' | 'facebook' | 'instagram' | 'twitter' | 'other';
export type HistorySort = 'recent' | 'oldest' | 'title' | 'size';

// AI types
export type AIProvider = 'gemini' | 'openai' | 'ollama' | 'proxy';
export type SummaryStyle = 'short' | 'concise' | 'detailed';

// Cookie/Authentication types
export type CookieMode = 'off' | 'browser' | 'file';
export type BrowserType = 'chrome' | 'firefox' | 'safari' | 'edge' | 'brave' | 'opera' | 'vivaldi';

export const BROWSER_OPTIONS: { value: BrowserType; label: string }[] = [
  { value: 'chrome', label: 'Google Chrome' },
  { value: 'firefox', label: 'Mozilla Firefox' },
  { value: 'safari', label: 'Safari' },
  { value: 'edge', label: 'Microsoft Edge' },
  { value: 'brave', label: 'Brave' },
  { value: 'opera', label: 'Opera' },
  { value: 'vivaldi', label: 'Vivaldi' },
];

export interface CookieSettings {
  mode: CookieMode;
  browser?: BrowserType;
  browserProfile?: string;
  filePath?: string;
}

export interface BrowserProfile {
  folder_name: string;   // Used for yt-dlp: "Profile 1"
  display_name: string;  // Shown to user: "Loc Nguyen"
}

export interface AIConfig {
  enabled: boolean;
  provider: AIProvider;
  api_key?: string;
  model: string;
  ollama_url?: string;
  proxy_url?: string; // Custom OpenAI-compatible API endpoint
  summary_style: SummaryStyle;
  summary_language: string;
  timeout_seconds?: number; // Timeout for AI generation (default 120s)
  transcript_languages?: string[]; // Languages to try for transcript extraction (order matters)
}

// Available languages (shared between transcript extraction and summary output)
export const LANGUAGE_OPTIONS = [
  { code: 'en', name: 'English' },
  { code: 'vi', name: 'Vietnamese' },
  { code: 'ja', name: 'Japanese' },
  { code: 'ko', name: 'Korean' },
  { code: 'zh-Hans', name: 'Chinese (Simplified)' },
  { code: 'zh-Hant', name: 'Chinese (Traditional)' },
  { code: 'th', name: 'Thai' },
  { code: 'id', name: 'Indonesian' },
  { code: 'hi', name: 'Hindi' },
  { code: 'pt-BR', name: 'Portuguese (Brazil)' },
  { code: 'es', name: 'Spanish' },
  { code: 'fr', name: 'French' },
  { code: 'de', name: 'German' },
  { code: 'pt', name: 'Portuguese' },
  { code: 'ru', name: 'Russian' },
] as const;

// Default transcript languages order
export const DEFAULT_TRANSCRIPT_LANGUAGES = ['en'];

export interface ModelOption {
  value: string;
  label: string;
}

export interface LanguageOption {
  value: string;
  label: string;
}

// ============================================
// Video Processing Types
// ============================================

export type ProcessingStatus = 'idle' | 'generating' | 'ready' | 'processing' | 'completed' | 'error';

export type ProcessingTaskType = 
  | 'cut' | 'extract_audio' | 'resize' | 'convert' 
  | 'burn_subtitles' | 'thumbnail' | 'gif' | 'speed' 
  | 'volume' | 'remove_audio' | 'merge' | 'compress'
  | 'rotate' | 'flip' | 'crop' | 'watermark' | 'custom';

export interface VideoMetadata {
  path: string;
  filename: string;
  duration: number; // seconds
  width: number;
  height: number;
  fps: number;
  video_codec: string;
  audio_codec: string;
  bitrate: number; // kbps
  file_size: number; // bytes
  format: string;
  has_audio: boolean;
}

export interface TimelineSelection {
  start: number; // seconds
  end: number; // seconds
}

export interface FFmpegCommandResult {
  command: string;
  explanation: string;
  estimated_size_mb: number;
  estimated_time_seconds: number;
  output_path: string;
  warnings: string[];
}

export interface ProcessingJob {
  id: string;
  input_path: string;
  output_path?: string;
  task_type: ProcessingTaskType;
  user_prompt?: string;
  ffmpeg_command: string;
  status: ProcessingStatus;
  progress: number;
  error_message?: string;
  input_metadata?: VideoMetadata;
  output_metadata?: VideoMetadata;
  created_at: string;
  completed_at?: string;
  ai_provider?: string;
  ai_model?: string;
}

export interface ProcessingProgress {
  job_id: string;
  percent: number;
  frame: number;
  total_frames: number;
  fps: number;
  speed: string;
  time: string;
  size: string;
}

export interface ProcessingPreset {
  id: string;
  name: string;
  description?: string;
  task_type: ProcessingTaskType;
  prompt_template: string;
  icon?: string;
  created_at: string;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant' | 'system' | 'complete';
  content: string;
  timestamp: string;
  command?: FFmpegCommandResult;
  outputPath?: string; // For 'complete' role
}

// Quick action definitions
export interface QuickAction {
  id: ProcessingTaskType;
  icon: string;
  label: string;
  description: string;
  needsInput?: 'format' | 'resolution' | 'speed' | 'file' | 'timestamp' | 'range';
}

export const QUICK_ACTIONS: QuickAction[] = [
  { id: 'cut', icon: '✂️', label: 'Cut/Trim', description: 'Cut video using timeline selection' },
  { id: 'extract_audio', icon: '🎵', label: 'Extract Audio', description: 'Extract audio track', needsInput: 'format' },
  { id: 'resize', icon: '📐', label: 'Resize', description: 'Change video resolution', needsInput: 'resolution' },
  { id: 'convert', icon: '🔄', label: 'Convert', description: 'Convert to different format', needsInput: 'format' },
  { id: 'burn_subtitles', icon: '📝', label: 'Burn Subtitles', description: 'Burn subtitles into video', needsInput: 'file' },
  { id: 'thumbnail', icon: '🖼️', label: 'Thumbnail', description: 'Extract frame as image', needsInput: 'timestamp' },
  { id: 'gif', icon: '🎞️', label: 'Create GIF', description: 'Create GIF from selection', needsInput: 'range' },
  { id: 'speed', icon: '⚡', label: 'Speed', description: 'Change playback speed', needsInput: 'speed' },
  { id: 'compress', icon: '📦', label: 'Compress', description: 'Reduce file size' },
  { id: 'remove_audio', icon: '🔇', label: 'Remove Audio', description: 'Remove audio track' },
  { id: 'rotate', icon: '🔃', label: 'Rotate', description: 'Rotate video 90°/180°/270°' },
  { id: 'merge', icon: '🔀', label: 'Merge', description: 'Merge multiple videos', needsInput: 'file' },
];
