import {
  Check,
  FileVideo,
  FolderOpen,
  HardDrive,
  ListVideo,
  Music,
  Radio,
  Settings2,
  Subtitles,
} from 'lucide-react';
import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { FFmpegRequiredDialog } from '@/components/FFmpegRequiredDialog';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Switch } from '@/components/ui/switch';
import type {
  AudioBitrate,
  DownloadSettings,
  Format,
  Quality,
  SubtitleFormat,
  SubtitleMode,
  VideoCodec,
} from '@/lib/types';
import { cn } from '@/lib/utils';

// Qualities that require FFmpeg for video+audio merging
const FFMPEG_REQUIRED_QUALITIES: Quality[] = ['best', '8k', '4k', '2k'];

function formatFileSize(bytes: number): string {
  if (bytes >= 1024 * 1024 * 1024) {
    return `${(bytes / (1024 * 1024 * 1024)).toFixed(1)} GB`;
  } else if (bytes >= 1024 * 1024) {
    return `${(bytes / (1024 * 1024)).toFixed(0)} MB`;
  } else if (bytes >= 1024) {
    return `${(bytes / 1024).toFixed(0)} KB`;
  }
  return `${bytes} B`;
}

const videoQualityKeys: { value: Quality; labelKey: string; shortLabelKey: string }[] = [
  { value: 'best', labelKey: 'quality.best', shortLabelKey: 'quality.bestShort' },
  { value: '8k', labelKey: 'quality.8k', shortLabelKey: 'quality.8kShort' },
  { value: '4k', labelKey: 'quality.4k', shortLabelKey: 'quality.4kShort' },
  { value: '2k', labelKey: 'quality.2k', shortLabelKey: 'quality.2kShort' },
  { value: '1080', labelKey: 'quality.1080', shortLabelKey: 'quality.1080Short' },
  { value: '720', labelKey: 'quality.720', shortLabelKey: 'quality.720Short' },
  { value: '480', labelKey: 'quality.480', shortLabelKey: 'quality.480Short' },
  { value: '360', labelKey: 'quality.360', shortLabelKey: 'quality.360Short' },
];

const videoFormatOptions: { value: Format; label: string }[] = [
  { value: 'mp4', label: 'MP4' },
  { value: 'mkv', label: 'MKV' },
  { value: 'webm', label: 'WebM' },
];

const audioFormatOptions: { value: Format; label: string }[] = [
  { value: 'mp3', label: 'MP3' },
  { value: 'm4a', label: 'M4A' },
  { value: 'opus', label: 'Opus' },
];

const subtitleModeKeys: { value: SubtitleMode; labelKey: string; descKey: string }[] = [
  { value: 'off', labelKey: 'settings.subtitleOff', descKey: 'settings.noSubtitles' },
  { value: 'auto', labelKey: 'settings.subtitleAuto', descKey: 'settings.autoGenerated' },
  { value: 'manual', labelKey: 'settings.subtitleManual', descKey: 'settings.selectLanguages' },
];

const subtitleFormatOptions: { value: SubtitleFormat; label: string }[] = [
  { value: 'srt', label: 'SRT' },
  { value: 'vtt', label: 'VTT' },
  { value: 'ass', label: 'ASS' },
];

const commonLanguageCodes = [
  'en',
  'vi',
  'ja',
  'ko',
  'zh-Hans',
  'zh-Hant',
  'es',
  'fr',
  'de',
  'pt',
  'ru',
];

interface SettingsPanelProps {
  settings: DownloadSettings;
  disabled?: boolean;
  totalFileSize?: number;
  ffmpegInstalled?: boolean;
  onQualityChange: (quality: Quality) => void;
  onFormatChange: (format: Format) => void;
  onVideoCodecChange: (codec: VideoCodec) => void;
  onAudioBitrateChange: (bitrate: AudioBitrate) => void;
  onConcurrentChange: (concurrent: number) => void;
  onPlaylistLimitChange: (limit: number) => void;
  onPlaylistToggle: () => void;
  onSelectFolder: () => void;
  // Subtitle callbacks
  onSubtitleModeChange: (mode: SubtitleMode) => void;
  onSubtitleLangsChange: (langs: string[]) => void;
  onSubtitleEmbedChange: (embed: boolean) => void;
  onSubtitleFormatChange: (format: SubtitleFormat) => void;
  // Live stream callback
  onLiveFromStartChange: (enabled: boolean) => void;
  // Navigation callback for FFmpeg dialog
  onGoToSettings?: () => void;
}

export function SettingsPanel({
  settings,
  disabled,
  totalFileSize,
  ffmpegInstalled = true,
  onQualityChange,
  onFormatChange,
  onVideoCodecChange,
  onAudioBitrateChange,
  onConcurrentChange,
  onPlaylistLimitChange,
  onPlaylistToggle,
  onSelectFolder,
  onSubtitleModeChange,
  onSubtitleLangsChange,
  onSubtitleEmbedChange,
  onSubtitleFormatChange,
  onLiveFromStartChange,
  onGoToSettings,
}: SettingsPanelProps) {
  const { t } = useTranslation('download');
  const [showFfmpegDialog, setShowFfmpegDialog] = useState(false);
  const [pendingQuality, setPendingQuality] = useState<Quality | null>(null);

  const isAudioOnly =
    settings.quality === 'audio' || ['mp3', 'm4a', 'opus'].includes(settings.format);
  const formatOptions = isAudioOnly ? audioFormatOptions : videoFormatOptions;
  const currentVideoQuality = isAudioOnly ? '1080' : settings.quality;

  const fileSizeDisplay = totalFileSize && totalFileSize > 0 ? formatFileSize(totalFileSize) : '';

  const handleModeChange = (mode: 'video' | 'audio') => {
    if (mode === 'audio') {
      onQualityChange('audio');
      if (!['mp3', 'm4a', 'opus'].includes(settings.format)) {
        onFormatChange('mp3');
      }
    } else {
      // Switch to video mode with last quality or default to 1080p
      if (settings.quality === 'audio') {
        onQualityChange('1080');
      }
      if (['mp3', 'm4a', 'opus'].includes(settings.format)) {
        onFormatChange('mp4');
      }
    }
  };

  const handleVideoQualityChange = (quality: Quality) => {
    // Check if FFmpeg is required but not installed
    if (FFMPEG_REQUIRED_QUALITIES.includes(quality) && !ffmpegInstalled) {
      setPendingQuality(quality);
      setShowFfmpegDialog(true);
      return;
    }
    onQualityChange(quality);
  };

  const applyQualityChange = (quality: Quality) => {
    onQualityChange(quality);
    if (quality === 'audio' && !['mp3', 'm4a', 'opus'].includes(settings.format)) {
      onFormatChange('mp3');
    }
    if (quality !== 'audio' && ['mp3', 'm4a', 'opus'].includes(settings.format)) {
      onFormatChange('mp4');
    }
  };

  const handleFfmpegDialogDismiss = () => {
    setShowFfmpegDialog(false);
    setPendingQuality(null);
  };

  const handleFfmpegDialogContinue = () => {
    setShowFfmpegDialog(false);
    if (pendingQuality) {
      applyQualityChange(pendingQuality);
    }
    setPendingQuality(null);
  };

  const outputFolderName = settings.outputPath
    ? settings.outputPath.split('/').pop() || settings.outputPath
    : 'Downloads';

  return (
    <>
      <div className="flex flex-wrap items-center gap-2">
        {/* Download Mode Toggle - Video/Audio */}
        <div className="flex items-center p-0.5 rounded-lg bg-muted/50 border border-border/50">
          <button
            type="button"
            onClick={() => handleModeChange('video')}
            disabled={disabled}
            className={cn(
              'h-8 px-3 rounded-md text-xs font-medium transition-all flex items-center gap-1.5',
              !isAudioOnly
                ? 'bg-background text-foreground shadow-sm'
                : 'text-muted-foreground hover:text-foreground',
            )}
          >
            <FileVideo className="w-3.5 h-3.5" />
            {t('settings.video')}
          </button>
          <button
            type="button"
            onClick={() => handleModeChange('audio')}
            disabled={disabled}
            className={cn(
              'h-8 px-3 rounded-md text-xs font-medium transition-all flex items-center gap-1.5',
              isAudioOnly
                ? 'bg-background text-foreground shadow-sm'
                : 'text-muted-foreground hover:text-foreground',
            )}
          >
            <Music className="w-3.5 h-3.5" />
            {t('settings.audio')}
          </button>
        </div>

        {/* Quality Select - Only for Video mode */}
        {!isAudioOnly && (
          <Select
            value={currentVideoQuality}
            onValueChange={handleVideoQualityChange}
            disabled={disabled}
          >
            <SelectTrigger
              className="w-[85px] h-9 text-xs bg-card/50 border-border/50"
              title={t('settings.videoQuality')}
            >
              <SelectValue>
                {t(
                  videoQualityKeys.find((q) => q.value === currentVideoQuality)?.shortLabelKey ||
                    'quality.bestShort',
                )}
              </SelectValue>
            </SelectTrigger>
            <SelectContent className="min-w-[180px]">
              {videoQualityKeys.map((opt) => (
                <SelectItem key={opt.value} value={opt.value} className="text-xs">
                  {t(opt.labelKey)}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        )}

        {/* Format Select */}
        <Select value={settings.format} onValueChange={onFormatChange} disabled={disabled}>
          <SelectTrigger
            className="w-[75px] h-9 text-xs bg-card/50 border-border/50"
            title={t('settings.outputFormat')}
          >
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            {formatOptions.map((opt) => (
              <SelectItem key={opt.value} value={opt.value} className="text-xs">
                {opt.label}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>

        {/* Playlist Toggle */}
        <button
          type="button"
          onClick={onPlaylistToggle}
          disabled={disabled}
          title={settings.downloadPlaylist ? t('settings.playlistOn') : t('settings.playlistOff')}
          className={cn(
            'h-9 px-2.5 rounded-md border text-xs flex items-center gap-1.5 transition-colors',
            settings.downloadPlaylist
              ? 'bg-primary/10 border-primary/30 text-primary'
              : 'bg-card/50 border-border/50 text-muted-foreground hover:text-foreground',
          )}
        >
          <ListVideo className="w-3.5 h-3.5" />
          <span className="hidden xs:inline">{t('settings.playlist')}</span>
        </button>

        {/* Subtitle Settings Popover */}
        <Popover>
          <PopoverTrigger asChild>
            <button
              type="button"
              disabled={disabled || isAudioOnly}
              title={
                isAudioOnly
                  ? t('settings.subtitlesNotAvailable')
                  : `${t('settings.subtitles')}: ${settings.subtitleMode}`
              }
              className={cn(
                'h-9 px-2.5 rounded-md border text-xs flex items-center gap-1.5 transition-colors',
                isAudioOnly && 'opacity-50 cursor-not-allowed',
                settings.subtitleMode !== 'off'
                  ? 'bg-primary/10 border-primary/30 text-primary'
                  : 'bg-card/50 border-border/50 text-muted-foreground hover:text-foreground',
              )}
            >
              <Subtitles className="w-3.5 h-3.5" />
              <span className="hidden xs:inline">CC</span>
            </button>
          </PopoverTrigger>
          <PopoverContent className="w-72 p-0" align="start" side="bottom" sideOffset={8}>
            {/* Header */}
            <div className="flex items-center gap-2 px-4 py-3 border-b bg-muted/30">
              <Subtitles className="w-4 h-4 text-primary" />
              <h4 className="text-sm font-medium">{t('settings.subtitles')}</h4>
            </div>

            <div className="p-4 space-y-4">
              {/* Mode Selection */}
              <div className="space-y-2">
                <Label className="text-[11px] text-muted-foreground">
                  {t('settings.subtitleMode')}
                </Label>
                <div className="grid grid-cols-3 gap-1.5">
                  {subtitleModeKeys.map((opt) => (
                    <button
                      type="button"
                      key={opt.value}
                      onClick={() => onSubtitleModeChange(opt.value)}
                      className={cn(
                        'h-8 px-2 rounded-md text-xs font-medium transition-colors',
                        settings.subtitleMode === opt.value
                          ? 'bg-primary text-primary-foreground'
                          : 'bg-muted/50 hover:bg-muted text-muted-foreground hover:text-foreground',
                      )}
                      title={t(opt.descKey)}
                    >
                      {t(opt.labelKey)}
                    </button>
                  ))}
                </div>
              </div>

              {/* Language Selection - Only show when mode is not 'off' */}
              {settings.subtitleMode !== 'off' && (
                <>
                  <div className="space-y-2">
                    <Label className="text-[11px] text-muted-foreground">
                      {settings.subtitleMode === 'auto'
                        ? t('settings.languagesAuto')
                        : t('settings.languages')}
                    </Label>
                    <div className="flex flex-wrap gap-1.5">
                      {commonLanguageCodes.map((code) => {
                        const isSelected = settings.subtitleLangs.includes(code);
                        return (
                          <button
                            type="button"
                            key={code}
                            onClick={() => {
                              if (isSelected) {
                                onSubtitleLangsChange(
                                  settings.subtitleLangs.filter((l) => l !== code),
                                );
                              } else {
                                onSubtitleLangsChange([...settings.subtitleLangs, code]);
                              }
                            }}
                            className={cn(
                              'h-7 px-2 rounded text-[11px] font-medium transition-colors flex items-center gap-1',
                              isSelected
                                ? 'bg-primary/15 text-primary border border-primary/30'
                                : 'bg-muted/50 text-muted-foreground hover:bg-muted hover:text-foreground border border-transparent',
                            )}
                            title={t(`languages.${code}`)}
                          >
                            {isSelected && <Check className="w-3 h-3" />}
                            {code.toUpperCase()}
                          </button>
                        );
                      })}
                    </div>
                    <p className="text-[10px] text-muted-foreground">
                      {settings.subtitleLangs.length === 0
                        ? t('settings.selectLanguage')
                        : t('settings.selectedLanguages', {
                            langs: settings.subtitleLangs.join(', ').toUpperCase(),
                          })}
                    </p>
                  </div>

                  {/* Format & Embed */}
                  <div className="grid grid-cols-2 gap-3">
                    <div className="space-y-1.5">
                      <Label className="text-[11px] text-muted-foreground">
                        {t('settings.format')}
                      </Label>
                      <Select
                        value={settings.subtitleFormat}
                        onValueChange={onSubtitleFormatChange}
                      >
                        <SelectTrigger className="h-8 text-xs">
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          {subtitleFormatOptions.map((opt) => (
                            <SelectItem key={opt.value} value={opt.value} className="text-xs">
                              {opt.label}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>

                    <div className="space-y-1.5">
                      <Label className="text-[11px] text-muted-foreground">
                        {t('settings.embed')}
                      </Label>
                      <div className="h-8 flex items-center justify-between px-3 rounded-md border bg-background">
                        <span className="text-xs text-muted-foreground">
                          {t('settings.inVideo')}
                        </span>
                        <Switch
                          checked={settings.subtitleEmbed}
                          onCheckedChange={onSubtitleEmbedChange}
                        />
                      </div>
                    </div>
                  </div>
                </>
              )}
            </div>
          </PopoverContent>
        </Popover>

        {/* Advanced Settings Popover */}
        <Popover>
          <PopoverTrigger asChild>
            <Button
              variant="ghost"
              size="sm"
              className="h-9 px-2.5 gap-1.5"
              disabled={disabled}
              title={t('settings.advanced')}
            >
              <Settings2 className="w-3.5 h-3.5" />
              <span className="hidden sm:inline text-xs">{t('settings.more')}</span>
            </Button>
          </PopoverTrigger>
          <PopoverContent className="w-72 p-0" align="end" side="bottom" sideOffset={8}>
            {/* Header */}
            <div className="flex items-center justify-between px-3 py-2 border-b bg-muted/30">
              <h4 className="text-xs font-medium">{t('settings.advanced')}</h4>
              {fileSizeDisplay && (
                <Badge variant="secondary" className="text-[10px] gap-1 h-5">
                  <HardDrive className="w-3 h-3" />
                  {fileSizeDisplay}
                </Badge>
              )}
            </div>

            {/* Content - Compact Layout with Scroll */}
            <div className="p-3 space-y-3 max-h-[50vh] overflow-y-auto">
              {/* Row 1: Codec & Bitrate */}
              <div className="grid grid-cols-2 gap-2">
                {/* Video Codec */}
                <div className="space-y-1">
                  <Label className="text-[10px] text-muted-foreground">
                    {isAudioOnly ? t('settings.audioCodec') : t('settings.videoCodec')}
                  </Label>
                  <Select
                    value={settings.videoCodec}
                    onValueChange={onVideoCodecChange}
                    disabled={disabled || isAudioOnly}
                  >
                    <SelectTrigger className="h-7 text-xs">
                      <SelectValue placeholder="Auto" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="h264" className="text-xs">
                        H.264
                      </SelectItem>
                      <SelectItem value="vp9" className="text-xs">
                        VP9
                      </SelectItem>
                      <SelectItem value="av1" className="text-xs">
                        AV1
                      </SelectItem>
                      <SelectItem value="auto" className="text-xs">
                        Auto
                      </SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                {/* Audio Bitrate */}
                <div className="space-y-1">
                  <Label className="text-[10px] text-muted-foreground">
                    {t('settings.audioQuality')}
                  </Label>
                  <Select
                    value={settings.audioBitrate}
                    onValueChange={onAudioBitrateChange}
                    disabled={disabled}
                  >
                    <SelectTrigger className="h-7 text-xs">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="auto" className="text-xs">
                        {t('settings.bestAudio')}
                      </SelectItem>
                      <SelectItem value="128" className="text-xs">
                        {t('settings.standardAudio')}
                      </SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>

              {/* Row 2: Concurrent & Playlist Limit */}
              <div className="grid grid-cols-2 gap-2">
                {/* Concurrent Downloads */}
                <div className="space-y-1">
                  <Label className="text-[10px] text-muted-foreground">
                    {t('settings.parallelDownloads')}
                  </Label>
                  <Select
                    value={String(settings.concurrentDownloads || 1)}
                    onValueChange={(v) => onConcurrentChange(Number(v))}
                    disabled={disabled}
                  >
                    <SelectTrigger className="h-7 text-xs">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {[1, 2, 3, 4, 5].map((n) => (
                        <SelectItem key={n} value={String(n)} className="text-xs">
                          {t('settings.atATime', { count: n })}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                {/* Playlist Limit */}
                <div className="space-y-1">
                  <Label className="text-[10px] text-muted-foreground">
                    {t('settings.playlistLimit')}
                  </Label>
                  <Select
                    value={String(settings.playlistLimit || 0)}
                    onValueChange={(v) => onPlaylistLimitChange(Number(v))}
                    disabled={disabled || !settings.downloadPlaylist}
                  >
                    <SelectTrigger
                      className={cn('h-7 text-xs', !settings.downloadPlaylist && 'opacity-50')}
                    >
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="0" className="text-xs">
                        {t('settings.unlimited')}
                      </SelectItem>
                      <SelectItem value="5" className="text-xs">
                        {t('settings.videos', { count: 5 })}
                      </SelectItem>
                      <SelectItem value="10" className="text-xs">
                        {t('settings.videos', { count: 10 })}
                      </SelectItem>
                      <SelectItem value="20" className="text-xs">
                        {t('settings.videos', { count: 20 })}
                      </SelectItem>
                      <SelectItem value="50" className="text-xs">
                        {t('settings.videos', { count: 50 })}
                      </SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>

              {/* Toggles Section - Compact */}
              <div className="space-y-2">
                {/* Playlist Toggle */}
                <div className="flex items-center justify-between py-1.5 px-2.5 rounded-md bg-muted/50">
                  <div className="flex items-center gap-2">
                    <ListVideo className="w-3.5 h-3.5 text-primary" />
                    <span className="text-[11px] font-medium">
                      {t('settings.downloadFullPlaylist')}
                    </span>
                  </div>
                  <Switch
                    checked={settings.downloadPlaylist}
                    onCheckedChange={onPlaylistToggle}
                    disabled={disabled}
                    className="scale-90"
                  />
                </div>

                {/* Live Stream Toggle */}
                <div className="flex items-center justify-between py-1.5 px-2.5 rounded-md bg-muted/50">
                  <div className="flex items-center gap-2">
                    <Radio className="w-3.5 h-3.5 text-red-500" />
                    <span className="text-[11px] font-medium">{t('settings.liveFromStart')}</span>
                  </div>
                  <Switch
                    checked={settings.liveFromStart}
                    onCheckedChange={onLiveFromStartChange}
                    disabled={disabled}
                    className="scale-90"
                  />
                </div>
              </div>

              {/* Output Folder */}
              <div className="space-y-1">
                <Label className="text-[10px] text-muted-foreground">{t('settings.saveTo')}</Label>
                <button
                  type="button"
                  onClick={onSelectFolder}
                  disabled={disabled}
                  className="w-full h-7 px-2.5 rounded-md border bg-background text-[11px] flex items-center gap-2 text-left hover:bg-muted/50 transition-colors"
                >
                  <FolderOpen className="w-3 h-3 text-muted-foreground flex-shrink-0" />
                  <span className="truncate flex-1 text-muted-foreground">
                    {settings.outputPath || t('settings.selectFolder')}
                  </span>
                </button>
              </div>
            </div>
          </PopoverContent>
        </Popover>

        {/* Spacer */}
        <div className="flex-1" />

        {/* Output Folder Button - Quick Access */}
        <button
          type="button"
          onClick={onSelectFolder}
          disabled={disabled}
          className="h-9 px-2.5 rounded-md border bg-card/50 border-border/50 text-xs flex items-center gap-1.5 text-muted-foreground hover:text-foreground transition-colors max-w-[140px]"
          title={
            settings.outputPath
              ? t('settings.outputFolder', { path: settings.outputPath })
              : t('settings.outputFolder', { path: t('settings.notSelected') })
          }
        >
          <FolderOpen className="w-3.5 h-3.5 flex-shrink-0" />
          <span className="truncate hidden xs:inline">{outputFolderName}</span>
        </button>

        {/* File Size Badge */}
        {fileSizeDisplay && (
          <Badge
            variant="outline"
            className="h-9 px-2.5 text-xs gap-1.5 hidden sm:flex"
            title={t('settings.totalFileSize')}
          >
            <HardDrive className="w-3.5 h-3.5" />
            {fileSizeDisplay}
          </Badge>
        )}
      </div>

      {/* FFmpeg Required Dialog */}
      {showFfmpegDialog && pendingQuality && (
        <FFmpegRequiredDialog
          quality={pendingQuality}
          onDismiss={handleFfmpegDialogDismiss}
          onContinue={handleFfmpegDialogContinue}
          onGoToSettings={onGoToSettings}
        />
      )}
    </>
  );
}
