import { useMemo } from 'react';
import { PluginDetailsConfigFlow } from './plugins/PluginDetailsConfigFlow';
import {
  PluginImportInstallActions,
  PluginImportInstallFlow,
} from './plugins/PluginImportInstallFlow';
import { PluginLogsWorkflowsFlow } from './plugins/PluginLogsWorkflowsFlow';
import {
  PluginWorkspaceActions,
  PluginWorkspaceCreateFlow,
} from './plugins/PluginWorkspaceCreateFlow';
import { usePostDownloadPluginsCard } from './plugins/usePostDownloadPluginsCard';

export function PostDownloadPluginsCard() {
  const controller = usePostDownloadPluginsCard();
  const workspaceActionsProps = useMemo(
    () => ({
      onOpenGuide: () => controller.setRuntimeGuideOpen(true),
      onAttachWorkspace: controller.handleAttachWorkspace,
      onOpenCreateDialog: controller.openCreateDialog,
    }),
    [controller.handleAttachWorkspace, controller.openCreateDialog, controller.setRuntimeGuideOpen],
  );
  const workspaceFlowProps = useMemo(
    () => ({
      createdWorkspace: controller.createdWorkspace,
      handleOpenWorkspacePath: controller.handleOpenWorkspacePath,
      handleAttachWorkspace: controller.handleAttachWorkspace,
      dismissCreatedWorkspace: controller.dismissCreatedWorkspace,
      createOpen: controller.createOpen,
      setCreateOpen: controller.setCreateOpen,
      resetCreateDialog: controller.resetCreateDialog,
      createPluginForm: controller.createPluginForm,
      updateCreatePluginForm: controller.updateCreatePluginForm,
      handlePickWorkspaceRoot: controller.handlePickWorkspaceRoot,
      creating: controller.creating,
      createPluginCanSubmit: controller.createPluginCanSubmit,
      handleCreatePlugin: controller.handleCreatePlugin,
      attachWorkspacePath: controller.attachWorkspacePath,
      setAttachWorkspacePath: controller.setAttachWorkspacePath,
      handleConfirmAttachWorkspace: controller.handleConfirmAttachWorkspace,
      runtimeGuideOpen: controller.runtimeGuideOpen,
      setRuntimeGuideOpen: controller.setRuntimeGuideOpen,
      providers: controller.providers,
      defaultProviders: controller.defaultProviders,
      handleSetDefaultProvider: controller.handleSetDefaultProvider,
      addCreatePluginConfigField: controller.addCreatePluginConfigField,
      createPluginConfigValidation: controller.createPluginConfigValidation,
      removeCreatePluginConfigField: controller.removeCreatePluginConfigField,
      updateCreatePluginConfigField: controller.updateCreatePluginConfigField,
      addCreatePluginConfigOption: controller.addCreatePluginConfigOption,
      updateCreatePluginConfigOption: controller.updateCreatePluginConfigOption,
      removeCreatePluginConfigOption: controller.removeCreatePluginConfigOption,
      toggleCreatePluginProvider: controller.toggleCreatePluginProvider,
      toggleCreatePluginTrigger: controller.toggleCreatePluginTrigger,
      toggleCreatePluginFilesystemPermission: controller.toggleCreatePluginFilesystemPermission,
      toggleCreatePluginToolPermission: controller.toggleCreatePluginToolPermission,
    }),
    [
      controller.addCreatePluginConfigField,
      controller.addCreatePluginConfigOption,
      controller.attachWorkspacePath,
      controller.createOpen,
      controller.createPluginCanSubmit,
      controller.createPluginConfigValidation,
      controller.createPluginForm,
      controller.createdWorkspace,
      controller.creating,
      controller.defaultProviders,
      controller.dismissCreatedWorkspace,
      controller.handleAttachWorkspace,
      controller.handleConfirmAttachWorkspace,
      controller.handleCreatePlugin,
      controller.handleOpenWorkspacePath,
      controller.handlePickWorkspaceRoot,
      controller.handleSetDefaultProvider,
      controller.providers,
      controller.removeCreatePluginConfigField,
      controller.removeCreatePluginConfigOption,
      controller.resetCreateDialog,
      controller.runtimeGuideOpen,
      controller.setAttachWorkspacePath,
      controller.setCreateOpen,
      controller.setRuntimeGuideOpen,
      controller.toggleCreatePluginFilesystemPermission,
      controller.toggleCreatePluginToolPermission,
      controller.toggleCreatePluginProvider,
      controller.toggleCreatePluginTrigger,
      controller.updateCreatePluginConfigField,
      controller.updateCreatePluginConfigOption,
      controller.updateCreatePluginForm,
    ],
  );
  const importActionsProps = useMemo(
    () => ({
      handleImportPackage: controller.handleImportPackage,
      inspecting: controller.inspecting,
    }),
    [controller.handleImportPackage, controller.inspecting],
  );
  const importFlowProps = useMemo(
    () => ({
      inspection: controller.inspection,
      installSource: controller.installSource,
      inspectionSigned: controller.inspectionSigned,
      inspectionCompatibilityEntries: controller.inspectionCompatibilityEntries,
      installAcknowledged: controller.installAcknowledged,
      setInstallAcknowledged: controller.setInstallAcknowledged,
      openPluginGuide: controller.openPluginGuide,
      dismissInspection: controller.dismissInspection,
      handleInstallInspection: controller.handleInstallInspection,
      installing: controller.installing,
      importDisclaimerOpen: controller.importDisclaimerOpen,
      setImportDisclaimerOpen: controller.setImportDisclaimerOpen,
      handleConfirmImportPackage: controller.handleConfirmImportPackage,
    }),
    [
      controller.dismissInspection,
      controller.handleConfirmImportPackage,
      controller.handleInstallInspection,
      controller.importDisclaimerOpen,
      controller.inspection,
      controller.inspectionCompatibilityEntries,
      controller.inspectionSigned,
      controller.installAcknowledged,
      controller.installSource,
      controller.installing,
      controller.openPluginGuide,
      controller.setImportDisclaimerOpen,
      controller.setInstallAcknowledged,
    ],
  );
  const detailsFlowProps = useMemo(
    () => ({
      loadPlugins: controller.loadPlugins,
      loading: controller.loading,
      error: controller.error,
      plugins: controller.plugins,
      expandedPluginId: controller.expandedPluginId,
      setExpandedPluginId: controller.setExpandedPluginId,
      runtimeStatuses: controller.runtimeStatuses,
      handleTogglePlugin: controller.handleTogglePlugin,
      handleRefreshPlugin: controller.handleRefreshPlugin,
      openPluginGuide: controller.openPluginGuide,
      handleOpenPluginLogs: controller.handleOpenPluginLogs,
      handleOpenPluginDirectory: controller.handleOpenPluginDirectory,
      handleUninstallPlugin: controller.handleUninstallPlugin,
      getTimeoutDraftValue: controller.getTimeoutDraftValue,
      setTimeoutDraftValue: controller.setTimeoutDraftValue,
      handleSavePluginTimeout: controller.handleSavePluginTimeout,
      handleResetPluginTimeout: controller.handleResetPluginTimeout,
      handleSetPluginProvider: controller.handleSetPluginProvider,
      handleApprovePermissions: controller.handleApprovePermissions,
      getConfigDraftValue: controller.getConfigDraftValue,
      setConfigDraftValue: controller.setConfigDraftValue,
      handlePickPluginConfigPath: controller.handlePickPluginConfigPath,
      handleSavePluginConfig: controller.handleSavePluginConfig,
      handleClearPluginConfig: controller.handleClearPluginConfig,
      pluginGuideDialog: controller.pluginGuideDialog,
      closePluginGuide: controller.closePluginGuide,
      permissionDialogPlugin: controller.permissionDialogPlugin,
      setPermissionDialogPlugin: controller.setPermissionDialogPlugin,
      permissionDialogState: controller.permissionDialogState,
      setPermissionDialogState: controller.setPermissionDialogState,
      handleEnablePluginWithPermissions: controller.handleEnablePluginWithPermissions,
      uninstallTarget: controller.uninstallTarget,
      setUninstallTarget: controller.setUninstallTarget,
      handleConfirmUninstallPlugin: controller.handleConfirmUninstallPlugin,
    }),
    [
      controller.closePluginGuide,
      controller.error,
      controller.expandedPluginId,
      controller.getConfigDraftValue,
      controller.getTimeoutDraftValue,
      controller.handleApprovePermissions,
      controller.handleClearPluginConfig,
      controller.handleConfirmUninstallPlugin,
      controller.handleEnablePluginWithPermissions,
      controller.handleOpenPluginDirectory,
      controller.handleOpenPluginLogs,
      controller.handlePickPluginConfigPath,
      controller.handleRefreshPlugin,
      controller.handleResetPluginTimeout,
      controller.handleSavePluginConfig,
      controller.handleSavePluginTimeout,
      controller.handleSetPluginProvider,
      controller.handleTogglePlugin,
      controller.handleUninstallPlugin,
      controller.loadPlugins,
      controller.loading,
      controller.openPluginGuide,
      controller.permissionDialogPlugin,
      controller.permissionDialogState,
      controller.pluginGuideDialog,
      controller.plugins,
      controller.runtimeStatuses,
      controller.setConfigDraftValue,
      controller.setExpandedPluginId,
      controller.setPermissionDialogPlugin,
      controller.setPermissionDialogState,
      controller.setTimeoutDraftValue,
      controller.setUninstallTarget,
      controller.uninstallTarget,
    ],
  );
  const logsWorkflowsFlowProps = useMemo(
    () => ({
      plugins: controller.plugins,
      workflowDefinitions: controller.workflowDefinitions,
      persistWorkflowDefinitions: controller.persistWorkflowDefinitions,
      logsOpen: controller.logsOpen,
      closeLogsDialog: controller.closeLogsDialog,
      selectedPlugin: controller.selectedPlugin,
      pluginLogs: controller.pluginLogs,
      pluginLogsTotal: controller.pluginLogsTotal,
      logsLoading: controller.logsLoading,
      logsLoadingMore: controller.logsLoadingMore,
      logsClearing: controller.logsClearing,
      pluginLogsHasMore: controller.pluginLogsHasMore,
      pluginLogsError: controller.pluginLogsError,
      selectedPluginId: controller.selectedPluginId,
      loadPluginLogs: controller.loadPluginLogs,
      handleLoadMorePluginLogs: controller.handleLoadMorePluginLogs,
      handleClearPluginLogs: controller.handleClearPluginLogs,
      clearLogsConfirmOpen: controller.clearLogsConfirmOpen,
      setClearLogsConfirmOpen: controller.setClearLogsConfirmOpen,
      handleConfirmClearPluginLogs: controller.handleConfirmClearPluginLogs,
    }),
    [
      controller.clearLogsConfirmOpen,
      controller.closeLogsDialog,
      controller.handleClearPluginLogs,
      controller.handleConfirmClearPluginLogs,
      controller.handleLoadMorePluginLogs,
      controller.loadPluginLogs,
      controller.logsClearing,
      controller.logsLoading,
      controller.logsLoadingMore,
      controller.logsOpen,
      controller.persistWorkflowDefinitions,
      controller.pluginLogs,
      controller.pluginLogsError,
      controller.pluginLogsHasMore,
      controller.pluginLogsTotal,
      controller.plugins,
      controller.selectedPlugin,
      controller.selectedPluginId,
      controller.setClearLogsConfirmOpen,
      controller.workflowDefinitions,
    ],
  );

  return (
    <>
      <div className="flex flex-wrap justify-end gap-2">
        <PluginWorkspaceActions {...workspaceActionsProps} />
        <PluginImportInstallActions {...importActionsProps} />
      </div>

      <PluginWorkspaceCreateFlow {...workspaceFlowProps} />
      <PluginImportInstallFlow {...importFlowProps} />
      <PluginDetailsConfigFlow {...detailsFlowProps} />
      <PluginLogsWorkflowsFlow {...logsWorkflowsFlowProps} />
    </>
  );
}
